name: Translate README

on:
  push:
    branches: [ main ]
    paths: [ 'README.md' ]

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4
      
      - name: Translate README
        uses: dephraiim/translate-readme@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          languages: es, fr, de, pt, ja
